CREATE TABLE "OrganizationSmsRegistrationApplication" (
  "id" TEXT NOT NULL,
  "orgId" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'DRAFT',
  "businessName" TEXT NOT NULL,
  "brandName" TEXT,
  "businessType" TEXT NOT NULL,
  "businessIndustry" TEXT NOT NULL,
  "businessRegistrationIdentifier" TEXT NOT NULL,
  "companyType" TEXT NOT NULL DEFAULT 'private',
  "businessIdentity" TEXT NOT NULL DEFAULT 'direct_customer',
  "businessRegionsOfOperation" TEXT NOT NULL DEFAULT 'USA_AND_CANADA',
  "websiteUrl" TEXT NOT NULL,
  "socialMediaProfileUrls" TEXT,
  "customerName" TEXT NOT NULL,
  "street" TEXT NOT NULL,
  "streetSecondary" TEXT,
  "city" TEXT NOT NULL,
  "region" TEXT NOT NULL,
  "postalCode" TEXT NOT NULL,
  "isoCountry" TEXT NOT NULL DEFAULT 'US',
  "authorizedFirstName" TEXT NOT NULL,
  "authorizedLastName" TEXT NOT NULL,
  "authorizedTitle" TEXT NOT NULL,
  "authorizedJobPosition" TEXT NOT NULL,
  "authorizedPhoneE164" TEXT NOT NULL,
  "authorizedEmail" TEXT NOT NULL,
  "brandContactEmail" TEXT,
  "campaignUseCase" TEXT NOT NULL,
  "campaignDescription" TEXT NOT NULL,
  "messageFlow" TEXT NOT NULL,
  "privacyPolicyUrl" TEXT,
  "termsOfServiceUrl" TEXT,
  "optInProofUrl" TEXT,
  "sampleMessage1" TEXT NOT NULL,
  "sampleMessage2" TEXT NOT NULL,
  "sampleMessage3" TEXT,
  "sampleMessage4" TEXT,
  "sampleMessage5" TEXT,
  "hasEmbeddedLinks" BOOLEAN NOT NULL DEFAULT false,
  "hasEmbeddedPhone" BOOLEAN NOT NULL DEFAULT false,
  "optInKeywords" TEXT,
  "optInMessage" TEXT,
  "optOutKeywords" TEXT,
  "optOutMessage" TEXT,
  "helpKeywords" TEXT,
  "helpMessage" TEXT,
  "estimatedMonthlyMessages" INTEGER,
  "desiredSenderNumberE164" TEXT,
  "customerConsentConfirmed" BOOLEAN NOT NULL DEFAULT false,
  "registrationSubmissionAuthorized" BOOLEAN NOT NULL DEFAULT false,
  "submittedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,

  CONSTRAINT "OrganizationSmsRegistrationApplication_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "OrganizationSmsRegistrationApplication_orgId_key" ON "OrganizationSmsRegistrationApplication"("orgId");
CREATE INDEX "OrganizationSmsRegistrationApplication_status_updatedAt_idx" ON "OrganizationSmsRegistrationApplication"("status", "updatedAt");

ALTER TABLE "OrganizationSmsRegistrationApplication"
  ADD CONSTRAINT "OrganizationSmsRegistrationApplication_orgId_fkey"
  FOREIGN KEY ("orgId") REFERENCES "Organization"("id") ON DELETE CASCADE ON UPDATE CASCADE;
